services:
  blub:
    build: .
    networks:
      - blub-network
    depends_on:
      - postgres-db
    env_file:
      - .env

  postgres-db:
    image: postgres:17-alpine
    networks:
      - blub-network
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password

networks:
  blub-network:
    driver: bridge

volumes:
  pgdata:
